### ISSUE TITLE
Please link gnuradio-pmt in Linux as build fails otherwise

### ISSUE THREAD

**Issue by barjac** [dl1ksv/gr-fcdproplus#12]
In Mageia linking fails without specifically adding gnuradio-pmt in lib/CMakeFiles.txt.
This patch fixes it:
diff -ur gr-fcdproplus_o/lib/CMakeLists.txt gr-fcdproplus/lib/CMakeLists.txt
--- gr-fcdproplus_o/lib/CMakeLists.txt	2015-01-14 12:40:58.000000000 +0000
+++ gr-fcdproplus/lib/CMakeLists.txt	2015-01-14 16:01:33.683860825 +0000
@@ -70,7 +70,7 @@
 
 target_link_libraries(gnuradio-fcdproplus ${fcdproplus_libs} ${Boost_LIBRARIES}
   ${GNURADIO_RUNTIME_LIBRARIES} ${GNURADIO_BLOCKS_LIBRARIES}
-  ${GNURADIO_AUDIO_LIBRARIES}
+  ${GNURADIO_AUDIO_LIBRARIES} ${GNURADIO_PMT_LIBRARIES}
 )
 
 if(APPLE)

**Comment by dl1ksv** [comment]
Where does this failure happen ? Building the lib or using the module.
Up to know this problem was only known on OSX. 
I'm using gentoo and it works. So I'd like to figure out why this happens on Mageia.

**Comment by barjac** [comment]
It's a linkage failure: https://paste.kde.org/pumnpntms
Sorry for paste but I see no way to attach.

**Comment by barjac** [comment]
With the patch: https://paste.kde.org/p7bwwghep

**Comment by dl1ksv** [comment]
Thanks for the info. That helped me to find an error in the cmake scripts, that only happened under certain circumstances.
Could you check if the fix solves your problem ?

**Comment by barjac** [comment]
Yes - thanks, the package builds fine now with latest git and the patch removed.
Closing  :)
