### ISSUE TITLE
gr-fcdproplus.pc.in has no "Version:" field

### ISSUE THREAD

**Issue by barjac** [dl1ksv/gr-fcdproplus#13]
I recently hit an issue building a package for Mageia 4 which fails in pkgconfig here:

Processing files: lib64gr-fcdproplus-devel-0-0.20150118git22f51738.1.mga4.x86_64
Finding  Provides: /usr/lib/rpm/mageia/filter.sh ' ' ' ' '/home/baz/rpmbuild/BUILDROOT/gr-fcdproplus-0-0.20150118git22f51738.1.mga4.x86_64' /usr/lib/rpm/mageia/find-provides
Package '/gnuradio-fcdproplus' has no Version: field
/usr/bin/pkg-config returned an error
error: /usr/lib/rpm/mageia/pkgconfigdeps.sh failed
error: /usr/lib/rpm/mageia/filter.sh failed: 100
error: Failed to find Provides:
Provides: gr-fcdproplus-devel = 0-0.20150118git22f51738.1.mga4 lib64gr-fcdproplus-devel = 0-0.20150118git22f51738.1.mga4 lib64gr-fcdproplus-devel(x86-64) = 0-0.20150118git22f51738.1.mga4
Requires(rpmlib): rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1

This does not occur in Mageia 5 (development) which has later versions of most deps.
Patching the .pc.in with "Version: 0" fixes the problem.
Versions of all packages installed in the build chroot are listed here:
https://paste.kde.org/pguaw27yg

**Comment by dl1ksv** [comment]
Fixed, please check.

**Comment by barjac** [comment]
Yes that fixes it, however I am a bit confused about the versioning. Is 0.0.1 the actual version, as I see 3.7 mentioned under 'releases' in github.
A brief explanation would be helpful.
Thanks in advance.

**Comment by dl1ksv** [comment]
3.7 is the version of gnuradio branch  gr-fcdproplus fits to. 0.0.1 would be the version number of gr-fcdproplus.
Do you think these numbers shoud be in sync ?

**Comment by barjac** [comment]
It would help from a packaging point of view if they were, as it's not obvious at present which versions are compatible.
However there may be other considerations of which I am unaware.
I only package ;)

**Comment by dl1ksv** [comment]
But this would mean that you have to update the version number of fcdp+ if gnuradio changes from 3.7 to 3.8 even if ther are no changes have to be made in fdcp+.
For knowing teh version of gnuradio we should perhaps use
Requires: gnuradio >=0 3.7

**Comment by barjac** [comment]
I'm not too concerned that the versions tie up with gnuradio, but rather that there is some progressive versioning that maybe changes when it's stable and /or features tied to specific gnuradio releases are added. 
To see a new version is available would indicate to me that "Hey guys we think it's stable at the moment and most bugs are fixed so now would be a good time to update your packages"  Rather than having to read all the commit logs and take a random stab in the dark.
Without real 'version' numbering for gr-fcdproplus it's not possible to require a specific version of it for other downstream projects should they need it e.g. gr-osmosdr. (although %{version}-%{release} may be used it again increases maintenance)
I am currently using the commit date and git hash in the package name, since no new 'versions' seem to have been released.
e.g. lib64gr-fcdproplus0-0.0.1-0.20150120git129ea634.1.mga4.x86_64.rpm
... which is rather messy.
Maybe I missed something.

**Comment by dl1ksv** [comment]
should be fixed now.

**Comment by barjac** [comment]
Yes Looks good - thanks.

It won't build though so I will file another bug
