### ISSUE TITLE
cmake reported gnuradio cmake modules not found on Raspbian

### ISSUE THREAD

**Issue by bg2bhc** [dl1ksv/gr-fcdproplus#15]
Hi dl1ksv,

I am trying to compile gr-fcdproplus on a Raspbian (Raspberry Pi 3) but cmake failed and reported gnuradio cmake modules not found (line 89).

The gnuradio is installed from deb and the version is 3.7.5.

I read the posts here https://github.com/dl1ksv/gr-fcdproplus/issues/14. The gnuradio cmake modules are not found at /usr/lib/cmake/gnuradio but at /usr/lib/arm-linux-gnueabihf. It looks to be a common status for Raspian according to https://cmake.org/Bug/view.php?id=15623. I edited Modules/Platform/UnixPaths.cmake but it doesn't works. 

Is there any way to solve this?

TNX & 73!

**Comment by dl1ksv** [comment]
Just try to insert 
 /usr/lib/arm-linux-gnueabihf
after
 /usr/lib/cmake/gnuradio

in cmake/Modules/FindGnuradioModules.cmake

**Comment by benblass** [comment]
ran into the same issue while building on Raspbian, just added 

`/usr/lib/arm-linux-gnueabihf/cmake/gnuradio`

 in cmake/Modules/FindGnuradioModules.cmake, no problem.

**Comment by dl1ksv** [comment]
Thanks !
I just pushed the change. This should fix this issue.

**Comment by piranha32** [comment]
Adding hardcoded paths to the cmake file is not a good solution. cmake knows about install prefix and should use to build the module path. The attached patch fixes the issue.
[FindGnuradioModules.patch.txt](https://github.com/dl1ksv/gr-fcdproplus/files/443200/FindGnuradioModules.patch.txt)

**Comment by dl1ksv** [comment]
FindGnuradioModules already uses the content of CMAKE_INSTALL_PREFIX to find the gnuradio cmake modules.
See the HINTS line. The hardcoded paths are only additional if the HINTS line fails.
Are  your gnuradio cmake files located in lib64 ? Then it would  be wise to add this information to the hints line.

**Comment by piranha32** [comment]
I saw it, but or some weird reason find_path is ignoring HINTS. I found this thread by googling for the error message. Despite providing install path to cmake, it was not able to find gnuradio modules. Doing the modification as in the patch fixed the problem.

**Comment by piranha32** [comment]
ok, I found the culprit: the path in HINTS is for 32 bit system. After adding lib64 to hints cmake  find_path finds gnuradio modules without the need to resort to the extra
[FindGnuradioModules.patch2.txt](https://github.com/dl1ksv/gr-fcdproplus/files/445848/FindGnuradioModules.patch2.txt)
 paths.

**Comment by dl1ksv** [comment]
I just applied the patch. Thanks for reporting and testing.
