### ISSUE TITLE
gr-fcdproplus-3.7.2-rc1 compilation fails on i386

### ISSUE THREAD

**Issue by yarda** [dl1ksv/gr-fcdproplus#16]
```
Scanning dependencies of target pygen_swig_b19a8
make[2]: Leaving directory '/builddir/build/BUILD/gr-fcdproplus-3.7.2-rc1/build'
make -f swig/CMakeFiles/pygen_swig_b19a8.dir/build.make swig/CMakeFiles/pygen_swig_b19a8.dir/build
make[2]: Entering directory '/builddir/build/BUILD/gr-fcdproplus-3.7.2-rc1/build'
make[2]: Leaving directory '/builddir/build/BUILD/gr-fcdproplus-3.7.2-rc1/build'
make[2]: *** No rule to make target 'swig/fcdproplus_swig.py', needed by 'swig/fcdproplus_swig.pyc'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:268: swig/CMakeFiles/pygen_swig_b19a8.dir/all] Error 2
make: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/gr-fcdproplus-3.7.2-rc1/build'
```
I tried building with make -j1, it didn't help. This could be problem of the GrSwig macro from gnuradio. I think the explicit dep for fcdproplus_swig.py should be there, otherwise it depends how cmake generates the makefile. If the fcdproplus_swig_swig_tag is before the pygen_ in the makefile then it works, otherwise it doesn't. I am not sure how cmake generates it, but it can have something to do with the architecture and timestamps. E.g. this build for the 3.7.2-rc1 release works on x86_64 but fails on i386, but if I try to build e5ff83966eff1675b0fc8334d1035011e0edb03e snapshot (from https://github.com/dl1ksv/gr-fcdproplus/archive/e5ff83966eff1675b0fc8334d1035011e0edb03e/gr-fcdproplus-e5ff83966eff1675b0fc8334d1035011e0edb03e.tar.gz) it works in i386, but fails with the same error on the ppc64. It seems to be 100% reproducible. Strange, but unfortunately I hadn't time to debug it.

Failed e5ff83966eff1675b0fc8334d1035011e0edb03e build (including the build log):
https://koji.fedoraproject.org/koji/taskinfo?taskID=27729589

Failed 3.7.2-rc1 scratch build:
https://koji.fedoraproject.org/koji/taskinfo?taskID=27785943

**Comment by dl1ksv** [comment]
First, you should use the latest commit. The library code itself hasn't changed, only the CMakeList files, as it didn't build on ubuntu.

I tested on ubuntu, gentoo and even on an older pi2 and it worked, so I have no real idea.
But in your build log I see that you patched
swig/CMakeLists.txt
swig/fcdproplus_swig.i

What are you changing ?
Both files are important for building fcdproplus_swig.py

**Comment by yarda** [comment]
Regarding the swig patch, I forgot it in the scratch build, but it should be harmless - it has been used just as a helper during diagnosis of the problem.

Nevertheless, I debugged the problem. It seems gnuradio bundles several cmake modules, including the UseSWIG.cmake, which has been unbundled from the Fedora gnuradio, so the cmake used the newer cmake version of the module instead of the bundled one. Unfortunately not all gnuradio cmake code is compatible with this new version of the module and it caused this strange behaviour.

I will open gnuradio ticket regarding this (whether unbundling is possible).

So this is not gr-fcdproplus issue, sorry for noise.
