### ISSUE TITLE
Pkgconfig "Requires: gnuradio >= 3.7" breaks rpmbuild generated deps

### ISSUE THREAD

**Issue by yarda** [dl1ksv/gr-fcdproplus#17]
It seems there is no .pc providing gnuradio in gnuradio-3.7.13.3, just the following deps has been extracted by rpmbuild:
```
pkgconfig(gnuradio-analog) = 3.7.13.3
pkgconfig(gnuradio-atsc) = 3.7.13.3
pkgconfig(gnuradio-audio) = 3.7.13.3
pkgconfig(gnuradio-blocks) = 3.7.13.3
pkgconfig(gnuradio-channels) = 3.7.13.3
pkgconfig(gnuradio-digital) = 3.7.13.3
pkgconfig(gnuradio-dtv) = 3.7.13.3
pkgconfig(gnuradio-fcd) = 3.7.13.3
pkgconfig(gnuradio-fec) = 3.7.13.3
pkgconfig(gnuradio-fft) = 3.7.13.3
pkgconfig(gnuradio-filter) = 3.7.13.3
pkgconfig(gnuradio-noaa) = 3.7.13.3
pkgconfig(gnuradio-pager) = 3.7.13.3
pkgconfig(gnuradio-qtgui) = 3.7.13.3
pkgconfig(gnuradio-runtime) = 3.7.13.3
pkgconfig(gnuradio-trellis) = 3.7.13.3
pkgconfig(gnuradio-uhd) = 3.7.13.3
pkgconfig(gnuradio-video-sdl) = 3.7.13.3
pkgconfig(gnuradio-vocoder) = 3.7.13.3
pkgconfig(gnuradio-wavelet) = 3.7.13.3
pkgconfig(gr-wxgui) = 3.7.13.3
pkgconfig(volk) = 1.4
```

I think rpmbuild is right here. The 'Requires: gnuradio >= 3.7' in gnuradio-fcdproplus.pc.in then causes rpmbuild to create requirement:
pkgconfig(gnuradio) >= 3.7 which cannot be satisfied by RPM/DNF which leads later to build failures like: https://kojipkgs.fedoraproject.org//work/tasks/185/27920185/root.log

I could add the dep manually to the RPM package, but I think better solution is to have in the  gnuradio-fcdproplus.pc.in e.g.: Requires: gnuradio-runtime >= 3.7.

**Comment by dl1ksv** [comment]
I removed the dependency for 3.7. None of the actual gnuradio components reports a version dependency.
I probably reintroduce a version dependency for gnuradio-runtime when switching to 3.8 .
Please check, if this works for you.

**Comment by yarda** [comment]
Yes, this seems to work. I fixed it the same way downstream. Thanks.

**Comment by dl1ksv** [comment]
Thanks !
