### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by YexiongLin** [dl1ksv/gr-fcdproplus#21]
-- Build type not specified: defaulting to release.
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   program_options
--   filesystem
--   system
--   regex
--   thread
--   unit_test_framework
--   chrono
--   atomic
-- User set python executable /usr/bin/python3
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable exact version "3.6.9") 
-- Found ALSA 1.1.3
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- Extracting version information from git describe...
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Doxxyfile found in DOXY_FILE_PATH-NOTFOUND
CMake Error: File /home/lyx/Xiaolab/gr-fcdproplus/swig/DOXY_FILE_PATH-NOTFOUND/Doxyfile.swig_doc.in does not exist.
CMake Error at cmake/Modules/GrSwig.cmake:65 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:121 (GR_SWIG_MAKE_DOCS)
  swig/CMakeLists.txt:41 (GR_SWIG_MAKE)

I have tried sudo apt-get install libgmp-dev and sudo apt-get install libgmp3-dev. But they did not work.

**Comment by dl1ksv** [comment]
That has nothing to do with gmp.
The 'Doxyfiles' are not found. That happens when your CMAKE_INSTALL_PREFIX does not point to your gnuradio installation.
