### ISSUE TITLE
error -28 "not enough bandwidth" on ehci-driver, x86 and ARM

### ISSUE THREAD

**Issue by MadBoat** [dl1ksv/gr-fcdproplus#5]
I took up this issue with Alexandru Csete in another thread, but he pointed out I was barking up the wrong tree. But the thread still contains a good description of the problem, and the solution I adopted. Please have a look. 

https://github.com/csete/gqrx/pull/88

**Comment by dl1ksv** [comment]
Does this problem still exist ?
I tested with a 4.5.0-rc7 kernel and the bandwidth message is gone.
The program works, although I see some messages like

> [  123.492138] retire_capture_urb: 4992 callbacks suppressed
[  128.492326] retire_capture_urb: 4991 callbacks suppressed

in the kernel log.
